### PR TITLE
Fixed GF during week 3, or the philly stage in general

### PR DESCRIPTION
**Pull request by MemeHoovy**
fixed her animation whenever the train was passing by

### CODE REVIEW

**Comment by Stilic** [comment]
i think a `blockDance` variable would be better cuz what you did doesn't allow custom gf dance speed on the philly stage

**Comment by MemeHoovy** [comment]
well I _did_ try something like that before, but it didn't work for some damn reason

**Comment by MemeHoovy** [comment]
OK wait, I think I got it

**Comment by MemeHoovy** [comment]
ok there we go

**Pull request merged**
